//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int SSID { get; set; }
        public string Designation1 { get; set; }
        public decimal Basic { get; set; }
        public decimal OT1 { get; set; }
        public decimal OT2 { get; set; }
        public decimal Intensive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
